spring.application.name=CostomerService
server.port=9069
spring.datasource.url=jdbc:mysql://localhost:3306/custormerDB
spring.datasource.username=root
Spring.datasource.password=n3u3da!
spring.datasource.driver-class=com.mysql.cj.jdbc.Driver